## Midterm Exam
### Harsh Shah

In [26]:
library(pracma)
library(MASS)

1. a. Transition matrix

In [17]:
A <- matrix(c(1, rep(0,5), 1/2, 0, 1/2, rep(0,3), rep(1/4,2), 0, rep(1/4,2), rep(0,3), 1/2, 0, 1/2, rep(0,4),
             1/2,0,1/2,rep(0,5), 1), nrow=6)
A

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0.5  0.25 0.0  0.0  0   
[2,] 0    0.0  0.25 0.0  0.0  0   
[3,] 0    0.5  0.00 0.5  0.0  0   
[4,] 0    0.0  0.25 0.0  0.5  0   
[5,] 0    0.0  0.25 0.5  0.0  0   
[6,] 0    0.0  0.00 0.0  0.5  1

b. Google matrix

In [5]:
#(2)Google matrix of A
#Determine the matrix K for A first
K <- matrix(c(rep(1/6,36)),nrow=6)
K

[,1]      [,2]      [,3]      [,4]      [,5]      [,6]     
[1,] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667
[2,] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667
[3,] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667
[4,] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667
[5,] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667
[6,] 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667 0.1666667

In [9]:
#Determine the matrix P for A because there are dangling node in A
P <- matrix(c(rep(1/6, 6), 1/2, 0, 1/2, rep(0,3), rep(1/4,2), 0, rep(1/4,2), rep(0,3), 1/2, 0, 1/2, rep(0,4),
             1/2,0,1/2,rep(1/6,6)), nrow=6)
P

[,1]      [,2] [,3] [,4] [,5] [,6]     
[1,] 0.1666667 0.5  0.25 0.0  0.0  0.1666667
[2,] 0.1666667 0.0  0.25 0.0  0.0  0.1666667
[3,] 0.1666667 0.5  0.00 0.5  0.0  0.1666667
[4,] 0.1666667 0.0  0.25 0.0  0.5  0.1666667
[5,] 0.1666667 0.0  0.25 0.5  0.0  0.1666667
[6,] 0.1666667 0.0  0.00 0.0  0.5  0.1666667

In [12]:
#Then determine the Google matrix of A
G <- matrix(c(0.85*P+0.15*K),nrow=6)

#Pint out the Google matrix of A
print(G)

          [,1]  [,2]   [,3]  [,4]  [,5]      [,6]
[1,] 0.1666667 0.450 0.2375 0.025 0.025 0.1666667
[2,] 0.1666667 0.025 0.2375 0.025 0.025 0.1666667
[3,] 0.1666667 0.450 0.0250 0.450 0.025 0.1666667
[4,] 0.1666667 0.025 0.2375 0.025 0.450 0.1666667
[5,] 0.1666667 0.025 0.2375 0.450 0.025 0.1666667
[6,] 0.1666667 0.025 0.0250 0.025 0.450 0.1666667


c. The graph has two dangling nodes. They are 1 & 6

d. No, graph doesn't have disconnected nodes

2. Shortest distance

In [16]:
y <- matrix(c(-1,-5,10), nrow=3)
y

[,1]
[1,] -1  
[2,] -5  
[3,] 10

In [20]:
u1 <- matrix(c(5,-2,1), nrow=3)
u1

[,1]
[1,]  5  
[2,] -2  
[3,]  1

In [21]:
u2 <- matrix(c(1,2,-1), nrow=3)
u2

[,1]
[1,]  1  
[2,]  2  
[3,] -1

In [30]:
a <- dot(y,u1)
b <- dot(u1,u1)
c <- dot(y,u2)
d <- dot(u2,u2)

In [32]:
y_bar <- (a/b)*u1 + (c/d)*u2
y_bar

[,1]
[1,] -1  
[2,] -8  
[3,]  4

In [34]:
dist <- norm(y - y_bar, '2')
round(dist, 2)

[1] 6.71

 Shortest distance is 6.71

3. Mileage

In [37]:
data <- read.csv('mileage.csv')
head(data)

DISP MILEAGE
1 1.8  31     
2 3.5  20     
3 3.2  22     
4 1.8  22     
5 2.8  20     
6 2.5  24

In [47]:
disp <- sqrt(data$DISP)
disp <- as.vector(disp)

In [49]:
disp <- 1/disp
disp

[1] 0.7453560 0.5345225 0.5590170 0.7453560 0.5976143 0.6324555 0.5976143
  [8] 0.5976143 0.5679618 0.5129892 0.5129892 0.5129892 0.5773503 0.4662524
 [15] 0.4822428 0.4822428 0.6741999 0.4188539 0.5679618 0.6454972 0.7453560
 [22] 0.4822428 0.4188539 0.5423261 0.6324555 0.5590170 0.6324555 0.5504819
 [29] 0.6741999 0.7071068 0.5504819 0.5063697 0.4385290 0.5504819 0.6085806
 [36] 0.4385290 0.6324555 0.7071068 0.4662524 0.7071068 0.4662524 0.5000000
 [43] 0.4662524 0.5000000 0.5773503 0.4822428 0.4822428 0.4822428 0.4188539
 [50] 0.6593805 0.5773503 0.7071068 0.7905694 0.5590170 0.7071068 0.7071068
 [57] 0.7071068 0.5773503 0.5504819 0.5590170 0.5000000 0.5000000 0.7453560
 [64] 0.5773503 0.5773503 0.5773503 0.4662524 0.4662524 0.7071068 0.5000000
 [71] 0.7453560 0.7453560 0.5976143 0.5590170 0.5590170 0.6324555 0.4662524
 [78] 0.5000000 0.6324555 0.5773503 0.7071068 0.6454972 0.7453560 0.5773503
 [85] 0.6454972 0.5773503 0.5504819 0.6454972 0.5000000 0.5679618 0.5129892
 [92] 0.5423261 0.7071068 0.5504819 0.5504819 0.6454972 0.5129892 0.5423261
 [99] 0.6454972 0.6324555 0.7071068 0.6593805 0.7254763 0.7254763 0.6324555
[106] 0.6741999 0.6741999 0.7905694 0.5423261 0.5773503 0.6741999 0.5773503
[113] 0.5773503 0.7453560 0.7071068 0.5773503 0.5423261 0.7071068 0.7071068
[120] 0.7453560 0.6454972

In [50]:
x <- as.matrix(cbind(rep(1, nrow(data)), disp))
head(x)

disp     
[1,] 1 0.7453560
[2,] 1 0.5345225
[3,] 1 0.5590170
[4,] 1 0.7453560
[5,] 1 0.5976143
[6,] 1 0.6324555

In [51]:
y <- as.matrix(data$MILEAGE)
head(y)

[,1]
[1,] 31  
[2,] 20  
[3,] 22  
[4,] 22  
[5,] 20  
[6,] 24

In [52]:
const = inv(t(x) %*% x) %*% t(x) %*% y
const

[,1]     
     -1.616648
disp 38.670211

In [58]:
cat("Model parameters are ", const)

Model parameters are  -1.616648 38.67021

In [53]:
lsq_error1 <- norm(y - x %*% const, '2')
cat("The least square error in Model is ", lsq_error1)

The least square error in Model is  22.50134

In [55]:
test_disp <- 1.8

In [56]:
model_pred <- c(1, test_disp) %*% const
model_pred

[,1]    
[1,] 67.98973

In [57]:
cat("Using Model, mpg of car is", model_pred)

Using Model, mpg of car is 67.98973